

class Bk:
    def __init__(self) -> None: ...

    def GLFWInit(self) -> None: ...

    def CreateWindow(self, arg0: int, arg1: int, arg2: str, arg3: bool, arg4: bool, /) -> None: ...

    def GetNKContext(self) -> "nk_context": ...

    def NewFrame(self) -> None: ...

    def Render(self) -> None: ...

    def PollEvents(self) -> None: ...

    def WaitEvents(self) -> None: ...

    def ShouldClose(self) -> bool: ...

    def SetShouldClose(self, arg: bool, /) -> None: ...

    def GetWindowSize(self) -> tuple[int, int]: ...

    def LS_SetExclusiveZone(self, arg: int, /) -> None: ...

    def LS_SetMargin(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> None: ...

    def LS_SetLayer(self, arg: int, /) -> None: ...

    def LS_SetAnchor(self, arg: int, /) -> None: ...

    def SetKeyboardFocus(self, arg: bool, /) -> None: ...

    def Shutdown(self) -> None: ...

    def LoadSvgImage(self, arg0: str, arg1: int, arg2: int, /) -> "nk_image": ...
